import { createStore } from "vuex";

const store = createStore({
  state: {
    musics: [
      {
        id: 0,
        tittle: "علاقه ",
        singer: "شادمهر عقیلی",
        img: "shadmehr2.png",
        like: "۲،۹۸۲",
        play: "۱۵۷هزار",
        album: "بی بندبار",
        release: "23 روز پیش",
        time: "۰۴:۴۲",
      },
      {
        id: 1,
        tittle: "  خاص",
        singer: "شادمهر عقیلی",
        img: "shadmehr1.png",
        like: "۲،۹۸۲",
        play: "۱۵۷هزار",
        album: "بی بندبار",
        release: "23 روز پیش",
        time: "۰۴:۴۲",
      },
      {
        id: 2,
        tittle: "ماه",
        singer: "شادمهر عقیلی",
        img: "shadmehr3.png",
        like: "۲،۹۸۲",
        play: "۱۵۷هزار",
        album: "بی بندبار",
        release: "23 روز پیش",
        time: "۰۴:۴۲",
      },
      {
        id: 2,
        tittle: "آسمون",
        singer: "شادمهر عقیلی",
        img: "shadmehr2.png",
        like: "۲،۹۸۲",
        play: "۱۵۷هزار",
        album: "بی بندبار",
        release: "23 روز پیش",
        time: "۰۴:۴۲",
      },
    ],
    musicHistoy: [
      {
        id: 0,
        tittle: "علاقه ",
        singer: "شادمهر عقیلی",
        img: "shadmehr1.png",
        like: "۲،۹۸۲",
        play: "۱۵۷هزار",
        album: "بی بندبار",
        release: "23 روز پیش",
        time: "۰۴:۴۲",
      },
      {
        id: 1,
        tittle: "  خاص",
        singer: "شادمهر عقیلی",
        img: "shadmehr3.png",
        like: "۲،۹۸۲",
        play: "۱۵۷هزار",
        album: "بی بندبار",
        release: "23 روز پیش",
        time: "۰۴:۴۲",
      },
      {
        id: 2,
        tittle: "ماه",
        singer: "شادمهر عقیلی",
        img: "shadmehr4.png",
        like: "۲،۹۸۲",
        play: "۱۵۷هزار",
        album: "بی بندبار",
        release: "23 روز پیش",
        time: "۰۴:۴۲",
      },
      {
        id: 2,
        tittle: "آسمون",
        singer: "شادمهر عقیلی",
        img: "shadmehr5.png",
        like: "۲،۹۸۲",
        play: "۱۵۷هزار",
        album: "بی بندبار",
        release: "23 روز پیش",
        time: "۰۴:۴۲",
      },
    ],
    playlists: [
      {
        id: 0,
        tittle: "غیرمعمولی",
        createBy: "ایجاد شده توسط فاطمه",
        img: "playlistCover1.png",
      },
      {
        id: 1,
        tittle: "علاقه ",
        createBy: "ایجاد شده توسط فاطمه",
        img: "playlistCover1.png",
      },
      {
        id: 2,
        tittle: "  خاص",
        createBy: "ایجاد شده توسط فاطمه",
        img: "playlistCover1.png",
      },
      {
        id: 3,
        tittle: "تماشا",
        createBy: "ایجاد شده توسط فاطمه",
        img: "playlistCover1.png",
      },
      {
        id: 4,
        tittle: "قاصدک",
        createBy: "ایجاد شده توسط فاطمه",
        img: "playlistCover1.png",
      },
      {
        id: 5,
        tittle: "قاصدک",
        createBy: "ایجاد شده توسط فاطمه",
        img: "playlistCover1.png",
      },
      {
        id: 6,
        tittle: "قاصدک",
        createBy: "ایجاد شده توسط فاطمه",
        img: "playlistCover1.png",
      },
      {
        id: 7,
        tittle: "قاصدک",
        createBy: "ایجاد شده توسط فاطمه",
        img: "playlistCover1.png",
      },
    ],
  },
  getters: {},
  mutations: {},
  actions: {},
});
export default store;
